---


- name: configure apache
  template:
    src: apache/ckan_default.conf.j2
    dest: /etc/apache2/sites-enabled/ckan_default.conf

- name: Configure CKAN
  template:
    src: ckan/production.ini.j2
    dest: "{{ CKAN_CONFIG }}/{{ CKAN_CONFIG_FILE }}"

- name: Copy andino configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: apache/apache.wsgi.j2, dest: "{{ CKAN_CONFIG }}/apache.wsgi"}
    - {src: ckan/datapusher.wsgi.j2, dest: /etc/ckan/datapusher.wsgi}
    - {src: ckan/export.map.json.j2, dest: "{{ CKAN_HOME }}/src/ckanext-datajson/ckanext/datajson/export_map/export.map.json"}

- name: Add user configuration scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: scripts/config/init_db.sh.j2, dest: "{{ CKAN_INIT }}/init_db.sh"}
    - {src: scripts/config/make_conf.sh.j2, dest: "{{ CKAN_INIT }}/make_conf.sh"}
    - {src: scripts/config/add_admin.sh.j2, dest: "{{ CKAN_INIT }}/add_admin.sh"}
    - {src: scripts/config/change_datapusher_url.sh.j2, dest: "{{ CKAN_INIT }}/change_datapusher_url.sh"}
    - {src: scripts/config/change_site_url.sh.j2, dest: "{{ CKAN_INIT }}/change_site_url.sh"}
    - {src: scripts/config/init.sh, dest: "{{ CKAN_INIT }}/init.sh"}
    - {src: scripts/config/init_dev.sh, dest: "{{ CKAN_INIT }}/init_dev.sh"}
    - {src: scripts/config/paster.sh.j2, dest: "{{ CKAN_INIT }}/paster.sh"}
    - {src: scripts/config/update_conf.sh.j2, dest: "{{ CKAN_INIT }}/update_conf.sh"}

- name: Add run scripts
  template:
    src: "scripts/{{ item.src }}"
    dest: "{{ CKAN_INIT }}/{{ item.dest }}"
  with_items:
    - {src: start_ckan.sh.j2, dest: start_ckan.sh}
    - {src: run_andino.sh, dest: run_andino.sh}
    - {src: run_gather_consumer.sh.j2, dest: run_gather_consumer.sh}
    - {src: run_fetch_consumer.sh.j2, dest: run_fetch_consumer.sh}
    - {src: run_harvest.sh.j2, dest: run_harvest.sh}
    - {src: start_cron.sh.j2, dest: start_cron.sh}
    - {src: run_clean_harvest.sh.j2, dest: run_clean_harvest.sh}
    - {src: run_tests.sh.j2, dest: run_tests.sh}
    - {src: run_rebuild_search.sh.j2, dest: run_rebuild_search.sh}
    - {src: run_update_tracking.sh.j2, dest: run_update_tracking.sh}
    - {src: start_rebuild_cron.sh.j2, dest: start_rebuild_cron.sh}
    - {src: sync_rebuild_tasks.sh.j2, dest: sync_rebuild_tasks.sh}

- name: Add tests scripts
  template:
    src: "scripts/tests/{{ item.src }}"
    dest: "{{ CKAN_INIT }}/tests/{{ item.dest }}"
  with_items:
    - {src: install_solr4.sh.j2, dest: install_solr4.sh}
    - {src: init_tests.sh.j2, dest: init_tests.sh}
    - {src: run_tests.sh.j2, dest: run_tests.sh}


- name: Copy default ckan config
  template:
    src: ckan/default.json.j2
    dest: "{{ CKAN_DIST_CONFIG }}/settings.json"

- name: Change mode default ckan config
  file:
    path: "{{ CKAN_DIST_CONFIG }}/settings.json"
    mode: 0666

- name: Change mode ckan init
  file:
    path: "{{ CKAN_INIT }}"
    recurse: yes
    mode: 0777

- name: Change mode ckan config
  file:
    path: "{{ CKAN_CONFIG }}"
    recurse: yes
    mode: 0777
