---

- name: work pls
  set_fact:
    system_settings_locale: "en_US.UTF-8"

- name: check if locale exists
  shell: "locale -a | grep -i {{ system_settings_locale | regex_replace('-', '') | quote }}"
  register: found_locale
  changed_when: no
  failed_when: no

#- name: create locale
#  command: localedef -i en_US -f UTF-8 en_US.UTF-8
#  when: found_locale.rc != 0

- name: instalar locales?
  apt:
    name: locales
    state: present

- name: Intento 2
  shell: sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen && LANG=en_US.UTF-8 && LANGUAGE=en_US:en && LC_ALL=en_US.UTF-8

- name: Gen locale
  locale_gen:
    name: "{{ system_settings_locale }}"

- name: Update locale
  shell: update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8

- name: Install software-properties-common
  apt: name=software-properties-common state=present update_cache=yes

- name: Add pgAdmin key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libevent-dev
    - libpq-dev
    - apache2
    - libapache2-mod-rpaf
    - build-essential
    - libxslt1-dev
    - libxml2-dev
    - python-dev
    - libffi-dev
    - libssl-dev
    - python-minimal
    - python-virtualenv
    - python-pip
    - libapache2-mod-wsgi
    - wget
    - curl
    - vim
    - ca-certificates
    - inotify-tools
    - git-core
    - pgadmin3
    - psmisc
    - gettext
    - supervisor
