sudo: required

services:
  - docker

before_install:
  - docker build -t datosgobar/portal-base:build base_portal
  - docker build -t datosgobar/portal-base-solr:build solr
  - docker build -t datosgobar/portal-base-nginx:build nginx

script:
  - echo "Success"

deploy:
  provider: script
  skip_cleanup: true
  script: "deploy/upload.sh"
  on:
    all_branches: true