sudo: required

services:
  - docker

before_install:
  - docker build -t datosgobar/portal-base:build .

script:
  - echo "Success"

deploy:
  provider: script
  skip_cleanup: true
  script: "deploy/upload.sh"
  on:
    all_branches: true