site_name: Portal Base
pages:
  - Home: 'index.md'
  - Images:
    - 'Portal base': 'imagenes/base_portal.md'
    - nginx: 'imagenes/nginx.md'
    - solr: 'imagenes/solr.md'
  - Deployment:
    - install: 'deploy/install.md'
    - update: 'deploy/update.md'
